name: mn-ligand
channels:
  - conda-forge
dependencies:
  - python=3.11
  - altair
  - gemmi>=0.7,<0.8
  - matplotlib
  - mdtraj
  - meeko=0.6.1
  - numpy
  - openpyxl>=3.1,<4
  - pandas
  - pillow
  - py3dmol
  - pyyaml>=6,<7
  - rdkit
  - scipy
  - seaborn
  - streamlit
  - typer
  - pip
