plugin = dict(
    extension_points={
        "ovo.workflow_page": [
            dict(
                module_name="ovo_ligand",
                title="Ligand structure preparation",
                path="ovo_ligand.app.pages.structure_preparation",
                category="Ligand-X",
                labels=["Ligand-X", "Preparation", "Docker"],
                short_description="Prepare protein and ligand inputs using a Docker-backed OVO wizard.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand docking",
                path="ovo_ligand.app.pages.docking",
                category="Ligand-X",
                labels=["Ligand-X", "Docking", "Docker"],
                short_description="Run a single receptor-ligand docking workflow directly through Docker.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Batch ligand docking",
                path="ovo_ligand.app.pages.batch_docking",
                category="Ligand-X",
                labels=["Ligand-X", "Docking", "Batch", "Docker"],
                short_description="Run batch docking for ligand collections directly through Docker.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Bound ligand MD",
                path="ovo_ligand.app.pages.bound_ligand_md",
                category="Ligand-X",
                labels=["Ligand-X", "MD", "PDB", "Docker"],
                short_description="Download a PDB, select a bound ligand, and run the Ligand-X MD protocol in Docker.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand molecular dynamics",
                path="ovo_ligand.app.pages.md",
                category="Ligand-X",
                labels=["Ligand-X", "MD", "Docker"],
                short_description="Submit an MD workflow skeleton with Docker container execution.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand ADMET prediction",
                path="ovo_ligand.app.pages.admet",
                category="Ligand-X",
                labels=["Ligand-X", "ADMET", "Docker"],
                short_description="Run ADMET prediction directly through Docker.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand Boltz-2 prediction",
                path="ovo_ligand.app.pages.boltz2",
                category="Ligand-X",
                labels=["Ligand-X", "Boltz-2", "GPU", "Docker"],
                short_description="Submit Boltz-2 ligand/protein prediction jobs with Docker container wiring.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand quantum chemistry",
                path="ovo_ligand.app.pages.qc",
                category="Ligand-X",
                labels=["Ligand-X", "Quantum chemistry", "Docker"],
                short_description="Run quantum chemistry jobs with Docker and external ORCA path configuration.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand ABFE",
                path="ovo_ligand.app.pages.abfe",
                category="Ligand-X",
                labels=["Ligand-X", "ABFE", "Free energy", "GPU", "Docker"],
                short_description="Submit ABFE jobs through a direct Docker workflow skeleton.",
                thumbnail=None,
            ),
            dict(
                module_name="ovo_ligand",
                title="Ligand RBFE",
                path="ovo_ligand.app.pages.rbfe",
                category="Ligand-X",
                labels=["Ligand-X", "RBFE", "Free energy", "GPU", "Docker"],
                short_description="Submit RBFE jobs through a direct Docker workflow skeleton.",
                thumbnail=None,
            ),
        ]
    }
)
